M48
; DRILL file KiCad 10.0.5 date 2026-08-12T21:35:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-12T21:35:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X141.5Y-104.5
X146.58Y-96.88
T2
X264.95Y-39.85
X264.95Y-65.15
M30
