name: Generate PDFs for KiCAD schematics

on:
  push:
    branches:
      - main
    paths:
      - '**/*.kicad_sch'

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create PDF files
        uses: sparkengineering/kicad-action@v4
        with:
          kicad_sch: ver3/mystery_box-v3.kicad_sch
          kicad_pcb: ver3/mystery_box-v3.kicad_pcb
          sch_pdf: true
          sch_pdf_file: mystery_box-v3.pdf
          pcb_gerbers: true

      - name: Add PDFs to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Added current PDF
          file_pattern: '*.pdf'
          branch: main
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          commit_user_name: GitHub Actions Bot
          commit_user_email: github-actions-bot@github.com
          skip_dirty_check: true
